### ISSUE TITLE
Allow other field name than "status"

### ISSUE THREAD

**Issue by nliautaud** [pauloamgomes/CockpitCMS-Moderation#1]
It seems to me that the plugin works only if the Moderation field is named `status`.
It would be logical to allow any name for this field, and that the system looks for the first `Moderation` type.

**Comment by pauloamgomes** [comment]
@nliautaud thanks for your suggestion, I also thought about it, but there are some possible issues, like what happens if the field name is changed?

**Comment by nliautaud** [comment]
@pauloamgomes I don't know the inner functioning, but isn't it possible to rely on the field type instead of the name completely, from end to end ? Is there anywhere you don't have access to the fields types ?
Note that it's a minor remark that may not be worth your time :)

**Comment by pauloamgomes** [comment]
@nliautaud well, the field type is enough to get the moderation field name and therefore the value, however my concern was not there, but more on what happens if the user changes later the field name, but can assume that is not an issue of the addon but cockpit himself (in such case its always possible to use the batch edit functionality and set the desired moderation value for multiple entries).

I committed a change that makes use of the field name instead of the pre defined status, so its possible to use any name (I still think that for consistency status shall be used across different collections). Also from now the moderation value is not retrieved in the API request, since in most of the cases the API would have an public access, is better to not expose a moderation field in the response.
