### ISSUE TITLE
Entry saves when hitting enter on text field

### ISSUE THREAD

**Issue by patricksebastien** [pauloamgomes/CockpitCMS-Moderation#12]
Trying my luck here, I opened a ticket on cockpit: https://github.com/agentejo/cockpit/issues/1302 but since I am using the moderation plugin I would like to know if there's something to do about it. Here's the issue:

---
Let's say I have a hook triggered when an entry is "Published", I am using the excellent plugin called Moderation. When creating a new entry with a text field, if I focus on the textfield, type something and hit Enter, the entry will be Published (the form will be submitted) and not Draft.

That's not good in my scenario because the hook send email when the entry is in Publish state.

How can I avoid this? Disabling the form submission when pressing Enter?
Thanks
---

Maybe not publishing but using the draft operation when using enter on a textfield?
Thanks

**Comment by pauloamgomes** [comment]
Hi @patricksebastien , thanks for reporting, that's core issue on Cockpit, as by default hitting enter on text input fields saves the entry... but since that has some implications on the Moderation addon and agree that hitting enter on text fields shoult not trigger a save I updated the moderation addon to deal with that, let me know if that works for you.

**Comment by patricksebastien** [comment]
Thank you very much!
