### ISSUE TITLE
Review workflow

### ISSUE THREAD

**Issue by gryphonmyers** [pauloamgomes/CockpitCMS-Moderation#21]
### Feature Suggestion

It would be useful to have a permissions structure allowing for users of certain roles to be prevented from publishing, but instead able to "request review" from a higher tier role, such that users of the higher tier role would be notified and prompted to approve or deny the draft. There is some missing UXD from my description, but users in our company are very quick to start brainstorming features like this once I show them how the plugin works :)

**Comment by pauloamgomes** [comment]
Thanks @gryphonmyers ,  that makes sense but probably will require some core changes in the addon, currently it supports a simple permission mechanism that can be added to user groups: manage, publish, unpublish and schedule.

What you are suggesting is a bit more about workflows then properly permissions, I started some time ago a task-based mechanism (you could assign tasks to other people and until they checked them publish was blocked - very similar to the tasks functionality in Contentful) but put that on hold due to lack of time. If I have the right time I may instead build a different addon when you can configure the workflow states (like a state-machine) and define permissions per state.
